
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ojoijcxrzprbemhxxqih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qb2lqY3hyenByYmVtaHh4cWloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MTk3MzEsImV4cCI6MjA2MzI5NTczMX0.hLUpbpgcnNhSHvyW7vp-oguWv4rIJnBbBiPSermzaPE";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase environment variables. Please check your .env file."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
